### PR TITLE
First exercises

### PR DESCRIPTION
**Pull request by codealchemy**
Working through [Ruby Koans](http://rubykoans.com/) exercises.

### CODE REVIEW

**Comment by ccollins** [comment]
Good :+1: 

Super shitty commit names though :)

**Comment by codealchemy** [comment]
@ccollins not too unique, but made those commit names a bit easier to make sense of :smile:

**Comment by ccollins** [comment]
These look good.  Going to merge.  Create new PRs for each batch.

**Comment by ccollins** [comment]
Cant merge! D'oh!

**Comment by codealchemy** [comment]
I got you @ccollins :smiling_imp:

**Pull request merged**
